# Generated by Django 4.1.5 on 2023-02-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0014_delete_officerreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('zipcode', models.CharField(max_length=50, null=True)),
                ('photo', models.FileField(upload_to='Userphoto/')),
                ('proof', models.FileField(upload_to='Userproof/')),
                ('password', models.CharField(max_length=50, unique=True)),
                ('doj', models.DateField(auto_now=True)),
                ('vstatus', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
