# Generated by Django 4.1.5 on 2023-02-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
        ('Guest', '0002_ownerreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vstatus', models.IntegerField(default=0)),
                ('requestdate', models.DateField(auto_now=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.rentdet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.userreg')),
            ],
        ),
    ]
