# Generated by Django 4.1.5 on 2023-02-23 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_ownerreg'),
        ('User', '0002_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=400)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_replay', models.TextField(default='not viewd yet', null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.ownerreg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userreg')),
            ],
        ),
    ]
