# Generated by Django 4.1.5 on 2023-02-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_replay',
            field=models.TextField(default='not viewed yet', null=True),
        ),
    ]
