# Generated by Django 4.1.5 on 2023-01-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
    ]
