# Generated by Django 4.1.5 on 2023-01-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_remove_district_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
    ]
