# Generated by Django 4.1.5 on 2023-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_place_country_remove_place_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='UserDocs/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
