# Generated by Django 4.1.5 on 2023-01-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_subadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.country'),
        ),
    ]
