# Generated by Django 4.1.5 on 2023-02-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_officerreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerreg',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
