# Generated by Django 4.1.5 on 2023-02-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_officerreg_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='officerreg',
        ),
    ]
