# Generated by Django 4.1.5 on 2023-02-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
